# Makefile generated by imake - do not edit!
# $Xorg: imake.c,v 1.6 2001/02/09 02:03:15 xorgcvs Exp $

# ----------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $Xorg: Imake.tmpl,v 1.4 2000/08/17 19:41:46 cpqbld Exp $
#
#
#
#
# $XFree86: xc/config/cf/Imake.tmpl,v 3.116 2002/01/15 21:22:33 keithp Exp $
# ----------------------------------------------------------------------

all::

.SUFFIXES: .i

# $Xorg: Imake.cf,v 1.4 2000/08/17 19:41:45 cpqbld Exp $

# $XFree86: xc/config/cf/Imake.cf,v 3.74 2001/11/16 16:47:50 dawes Exp $

# Keep cpp from replacing path elements containing 1/i586/i686

# Keep this order! s390x has also __s390__ defined.

#  for compatibility with 3.3.x

# -----------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $TOG: site.sample /main/r64_final/1 1998/02/05 16:28:49 kaleb $

# site:  $XFree86: xc/config/cf/site.def,v 3.24 2000/06/25 20:17:29 dawes Exp $

# $XFree86: xc/config/cf/xf86site.def,v 3.179 2002/01/16 18:36:00 dawes Exp $

# ----------------------------------------------------------------------
# platform-specific configuration parameters - edit linux.cf to change

# platform:  $Xorg: linux.cf,v 1.3 2000/08/17 19:41:47 cpqbld Exp $

# platform:  $XFree86: xc/config/cf/linux.cf,v 3.175 2002/01/15 21:22:31 keithp Exp $

# operating system:  SuSE Linux [ELF] (2.4.18)
# libc:	(6.2.5)
# binutils:	(211)

# This may change soon

# $Xorg: lnxLib.rules,v 1.3 2000/08/17 19:41:47 cpqbld Exp $
# $XFree86: xc/config/cf/lnxLib.rules,v 3.42 2002/01/16 00:39:59 keithp Exp $

# $XFree86: xc/config/cf/xfree86.cf,v 3.388 2002/01/03 22:51:54 alanh Exp $

# $Xorg: xfree86.cf,v 1.4 2000/08/17 19:41:49 cpqbld Exp $

AFB_DEFS = -DUSE_AFB

DRIVERSDKDIR = $(USRLIBDIR)/Server
DRIVERSDKMODULEDIR = $(USRLIBDIR)/Server/modules
DRIVERSDKINCLUDEDIR = $(USRLIBDIR)/Server/include

       XF86SRC = $(SERVERSRC)/hw/xfree86
    XF86COMSRC = $(XF86SRC)/common
 XF86PARSERSRC = $(XF86SRC)/parser
     XF86OSSRC = $(XF86SRC)/os-support
 XF86DRIVERSRC = $(XF86SRC)/drivers
     DRIVERSRC = $(XF86DRIVERSRC)

        XFREE86DOCDIR = $(DOCDIR)
      XFREE86PSDOCDIR = $(DOCPSDIR)
    XFREE86HTMLDOCDIR = $(DOCHTMLDIR)
XFREE86JAPANESEDOCDIR = $(DOCDIR)/Japanese

# $Xorg: xf86.rules,v 1.3 2000/08/17 19:41:48 cpqbld Exp $

# $XFree86: xc/config/cf/xf86.rules,v 3.34 2001/07/19 02:22:44 tsi Exp $

# ----------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $TOG: site.sample /main/r64_final/1 1998/02/05 16:28:49 kaleb $

# site:  $XFree86: xc/config/cf/site.def,v 3.24 2000/06/25 20:17:29 dawes Exp $

# ---------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $Xorg: Imake.rules,v 1.3 2000/08/17 19:41:46 cpqbld Exp $
#
#
#
#
# rules:  $XFree86: xc/config/cf/Imake.rules,v 3.102 2001/12/17 20:00:37 dawes Exp $

 _NULLCMD_ = @ echo -n

GLIDE2INCDIR = /usr/include/glide

GLIDE3INCDIR = /usr/include/glide3

GLIDE3LIBNAME = glide3

TKLIBNAME =

TKLIBDIR =

TCLLIBNAME =

TCLIBDIR =

          PATHSEP = /
            SHELL = /bin/sh -e

              TOP = .
      CURRENT_DIR = .

            IMAKE = imake
           DEPEND = gccmakedep
        MKDIRHIER = mkdir -p
          REVPATH = revpath
    EXPORTLISTGEN =
             RMAN = rman
      RMANOPTIONS = -f HTML
        CONFIGSRC = $(TOP)/config
         IMAKESRC = $(CONFIGSRC)/imake
        DEPENDSRC = $(CONFIGSRC)/util

          INCROOT = /usr/X11R6/include
        USRLIBDIR = /usr/X11R6/lib
           VARDIR = /var
        VARLIBDIR = $(VARDIR)/lib
  SYSTEMUSRLIBDIR = /usr/lib
  SYSTEMUSRINCDIR = /usr/include
         SHLIBDIR = /usr/X11R6/lib
       LINTLIBDIR = $(USRLIBDIR)/lint
          MANPATH = /usr/X11R6/man
    MANSOURCEPATH = $(MANPATH)/man
           MANDIR = $(MANSOURCEPATH)1
        LIBMANDIR = $(MANSOURCEPATH)3
       FILEMANDIR = $(MANSOURCEPATH)5
       MISCMANDIR = $(MANSOURCEPATH)$(MISCMANSUFFIX)
     DRIVERMANDIR = $(MANSOURCEPATH)$(DRIVERMANSUFFIX)
     LOGDIRECTORY = $(VARDIR)/log

        VARRUNDIR = $(VARDIR)/run

         VARDBDIR = /var/lib

               AR = ar clq

  BOOTSTRAPCFLAGS =

               CC = gcc
               AS = as

.SUFFIXES: .cc

              CXX = c++

          CXXFILT = c++filt
           CXXLIB =
    CXXDEBUGFLAGS = -O2 -march=i486 -mcpu=i686
CXXDEPENDINCLUDES =
 CXXEXTRA_DEFINES =
CXXEXTRA_INCLUDES =
   CXXSTD_DEFINES = -Dlinux -D__i386__ -D_POSIX_C_SOURCE=199309L -D_POSIX_SOURCE -D_XOPEN_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE    $(CXXPROJECT_DEFINES)
       CXXOPTIONS =
      CXXINCLUDES = $(INCLUDES) $(TOP_INCLUDES) $(CXXEXTRA_INCLUDES)
       CXXDEFINES = $(CXXINCLUDES) $(CXXSTD_DEFINES) $(THREADS_CXXDEFINES) $(DEFINES) $(CXXEXTRA_DEFINES)
         CXXFLAGS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(THREADS_CXXFLAGS) $(CXXDEFINES)

         COMPRESS = compress
          GZIPCMD = gzip

              CPP = /lib/cpp $(STD_CPP_DEFINES)
           RAWCPP = /lib/cpp -undef $(STD_CPP_OPTIONS)
    PREPROCESSCMD = gcc -E $(STD_CPP_DEFINES)

          INSTALL = install
     INSTALLFLAGS = -c

               LD = ld

              LEX = flex -l
               M4 = m4
          M4FLAGS =
           LEXLIB = -lfl
             YACC = bison -y
           CCYACC = bison -y

             LINT = lint

      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv -f
               CP = cp

           RANLIB = ranlib

  RANLIBINSTFLAGS =

               RM = rm -f
             PERL = perl
         PERLOPTS =
        MANSUFFIX = 1x
     LIBMANSUFFIX = 3x
    FILEMANSUFFIX = 5x
    MISCMANSUFFIX = 7
  DRIVERMANSUFFIX = 4
     MANSRCSUFFIX = man
     MANNEWSUFFIX = _man
          MANDEFS = -D__apploaddir__=$(XAPPLOADDIR) -D__filemansuffix__=$(FILEMANSUFFIX) -D__miscmansuffix__=$(MISCMANSUFFIX) -D__drivermansuffix__=$(DRIVERMANSUFFIX) -D__projectroot__=$(PROJECTROOT) $(XORGMANDEFS) $(VENDORMANDEFS)

   COMPRESSMANCMD = gzip -n

            TROFF = groff -Tps
            NROFF = nroff
         MSMACROS = -ms
        MANMACROS = -man
              TBL = tbl
              EQN = eqn
             NEQN = neqn
              COL = col
         COLFLAGS = -b

            MODCC = gcc

           MODCPP = /lib/cpp
        MODCFLAGS = $(CFLAGS)
            MODAS = as
       MODASFLAGS =

            MODLD = ld

       MODLDFLAGS =
MODLDCOMBINEFLAGS = -r
            MODAR = ar clq

        MODRANLIB = ranlib

     STD_INCLUDES =
  STD_CPP_OPTIONS = -traditional
  STD_CPP_DEFINES = -traditional -Dlinux -D__i386__ -D_POSIX_C_SOURCE=199309L -D_POSIX_SOURCE -D_XOPEN_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE    $(PROJECT_DEFINES)
      STD_DEFINES = -Dlinux -D__i386__ -D_POSIX_C_SOURCE=199309L -D_POSIX_SOURCE -D_XOPEN_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE    $(PROJECT_DEFINES)
 EXTRA_LOAD_FLAGS =
  EXTRA_LDOPTIONS =
  EXTRA_LIBRARIES =
             TAGS = ctags

   PARALLELMFLAGS =

    SHAREDCODEDEF =
         SHLIBDEF =

     SHLIBLDFLAGS = -shared

         PICFLAGS = -fPIC

      CXXPICFLAGS = -fPIC

    PROTO_DEFINES = -DFUNCPROTO=15 -DNARROWPROTO

     INSTPGMFLAGS =

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4711
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -m 4711

      PROJECTROOT = /usr/X11R6

      CDEBUGFLAGS = -O2 -march=i486 -mcpu=i686
        CCOPTIONS =

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(INSTALLED_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(PROTO_DEFINES) $(THREADS_DEFINES) $(MODULE_DEFINES) $(DEFINES) $(EXTRA_DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(THREADS_CFLAGS) $(MODULE_CFLAGS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES) $(DEPEND_DEFINES)
         LDPRELIB = -L$(USRLIBDIR)
        LDPOSTLIB =
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)  $(EXTRA_LDOPTIONS) $(THREADS_LDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)
     CXXLDOPTIONS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(EXTRA_LDOPTIONS) $(THREADS_CXXLDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)

           LDLIBS = $(LDPOSTLIBS) $(THREADS_LIBS) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

           CCLINK = $(CC)

          CXXLINK = $(CXX)

     LDSTRIPFLAGS = -x
   LDCOMBINEFLAGS = -r
      DEPENDFLAGS =
   DEPEND_DEFINES = -DUSE_MAKEDEPEND

# Not sure this belongs here
         TKLIBDIR =
         TKINCDIR =
        TKLIBNAME =
        TKLIBRARY = -L$(TKLIBDIR) -l$(TKLIBNAME)
        TCLLIBDIR =
        TCLINCDIR =
       TCLLIBNAME =
       TCLLIBRARY = -L$(TCLLIBDIR) -l$(TCLLIBNAME)

        MACROFILE = linux.cf
           RM_CMD = $(RM)

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/X11.tmpl 			$(IRULESRC)/site.def $(IRULESRC)/$(MACROFILE) 			$(IRULESRC)/xfree86.cf $(IRULESRC)/xf86.rules $(IRULESRC)/xf86site.def $(IRULESRC)/host.def $(EXTRA_ICONFIGFILES)

# $TOG: Motif.rules /main/8 1999/03/22 15:12:48 mgreess $

# $Xorg: X11.rules,v 1.4 2000/08/17 19:41:46 cpqbld Exp $

# $XFree86: xc/config/cf/X11.rules,v 1.6 2001/01/17 16:22:31 dawes Exp $

# $TOG: Motif.tmpl /main/6 1999/05/19 17:00:05 mgreess $

# ----------------------------------------------------------------------
# X Window System Build Parameters and Rules
# $Xorg: X11.tmpl,v 1.6 2000/08/17 19:41:46 cpqbld Exp $
#
#
#
#
# $XFree86: xc/config/cf/X11.tmpl,v 1.141 2002/01/15 22:55:26 herrb Exp $

XORGRELSTRING = Release 6.6
XORGMANNAME = X Version 11

VENDORMANNAME = XFree86
VENDORMANVERSION = Version `echo 4 2 0 | sed 's/ /./g'`

STICKY_DEFINES = -DHAS_STICKY_DIR_BIT

FCHOWN_DEFINES = -DHAS_FCHOWN

# -----------------------------------------------------------------------
# X Window System make variables; these need to be coordinated with rules

             XTOP = $(TOP)
           BINDIR = /usr/X11R6/bin
     BUILDINCROOT = $(TOP)/exports
      BUILDINCDIR = $(BUILDINCROOT)/include
      BUILDINCTOP = ../..
      BUILDLIBDIR = $(TOP)/exports/lib
      BUILDLIBTOP = ../..
      BUILDBINDIR = $(TOP)/exports/bin
      BUILDBINTOP = ../..
   BUILDMODULEDIR = $(BUILDLIBDIR)/modules
   BUILDMODULETOP = $(BUILDLIBTOP)/..
    XBUILDINCROOT = $(XTOP)/exports
     XBUILDINCDIR = $(XBUILDINCROOT)/include/X11
     XBUILDINCTOP = ../../..
     XBUILDBINDIR = $(XBUILDINCROOT)/bin
           INCDIR = $(INCROOT)
           ADMDIR = /usr/adm
           LIBDIR = /usr/X11R6/lib/X11
       LIBEXECDIR = /usr/X11R6/libexec
        MODULEDIR = $(USRLIBDIR)/modules
   TOP_X_INCLUDES =

        ETCX11DIR = /etc/X11

          CONFDIR = $(ETCX11DIR)

           DOCDIR = $(LIBDIR)/doc
       DOCHTMLDIR = $(DOCDIR)/html
         DOCPSDIR = $(DOCDIR)/PostScript
          FONTDIR = $(LIBDIR)/fonts
     ENCODINGSDIR = $(FONTDIR)/encodings
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = /etc/X11/xdm
        XDMVARDIR = $(VARLIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
           XSMDIR = $(LIBDIR)/xsm
           NLSDIR = $(LIBDIR)/nls
       XLOCALEDIR = $(LIBDIR)/locale
        PEXAPIDIR = $(LIBDIR)/PEX
      LBXPROXYDIR = $(LIBDIR)/lbxproxy
  PROXYMANAGERDIR = $(LIBDIR)/proxymngr
        XPRINTDIR = $(LIBDIR)/xserver
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

              RGB = $(BINDIR)/rgb
            FONTC = $(BINDIR)/bdftopcf
        MKFONTDIR = $(BINDIR)/mkfontdir
         XFTCACHE = $(BINDIR)/xftcache
      MKHTMLINDEX = $(BINDIR)/mkhtmlindex
          UCS2ANY = $(BINDIR)/ucs2any.pl
      BDFTRUNCATE = $(BINDIR)/bdftruncate.pl
     UCSMAPPREFIX = $(FONTDIR)/util/map-

     HTMLINDEXCMD = HtmlIndexCmd

       DOCUTILSRC = $(XTOP)/doc/util
        CLIENTSRC = $(TOP)/clients
          DEMOSRC = $(TOP)/demos
       XDOCMACROS = $(DOCUTILSRC)/macros.t
       XIDXMACROS = $(DOCUTILSRC)/indexmacros.t
       PROGRAMSRC = $(TOP)/programs
           LIBSRC = $(XTOP)/lib
          FONTSRC = $(XTOP)/fonts
     ENCODINGSSRC = $(FONTSRC)/encodings
       INCLUDESRC = $(BUILDINCROOT)/include
      XINCLUDESRC = $(INCLUDESRC)/X11
        SERVERSRC = $(XTOP)/programs/Xserver
       CONTRIBSRC = $(XTOP)/../contrib
   UNSUPPORTEDSRC = $(XTOP)/unsupported
           DOCSRC = $(XTOP)/doc
           RGBSRC = $(XTOP)/programs/rgb
      BDFTOPCFSRC = $(PROGRAMSRC)/bdftopcf
     MKFONTDIRSRC = $(PROGRAMSRC)/mkfontdir
    FONTSERVERSRC = $(PROGRAMSRC)/xfs
       FONTINCSRC = $(XTOP)/include/fonts
        EXTINCSRC = $(XTOP)/include/extensions
      FTSOURCEDIR = $(TOP)/extras/FreeType
     XTTSOURCEDIR = $(TOP)/extras/X-TrueType
       MESASRCDIR = $(TOP)/extras/Mesa
  OGLSAMPLESRCDIR = $(TOP)/extras/ogl-sample
        PSWRAPSRC = $(XTOP)/config/pswrap
     TRANSCOMMSRC = $(LIBSRC)/xtrans
   TRANS_INCLUDES = -I$(TRANSCOMMSRC)
 CONNECTION_FLAGS = -DUNIXCONN -DTCPCONN $(STICKY_DEFINES) $(FCHOWN_DEFINES)

      XORGMANDEFS = -D__xorgversion__='"$(XORGRELSTRING)" "$(XORGMANNAME)"'
    VENDORMANDEFS = -D__vendorversion__="$(VENDORMANVERSION) $(VENDORMANNAME)"

       XENVLIBDIR = $(USRLIBDIR)
   CLIENTENVSETUP = LD_LIBRARY_PATH=$(MOTIFENVLIBDIR):$(XENVLIBDIR)

# $Xorg: lnxLib.tmpl,v 1.3 2000/08/17 19:41:47 cpqbld Exp $
# $XFree86: xc/config/cf/lnxLib.tmpl,v 3.14 2001/08/01 00:44:32 tsi Exp $

          XLIBSRC = $(LIBSRC)/X11

SOXLIBREV = 6.2
DEPXONLYLIB =
XONLYLIB =  -lX11

LINTXONLY = $(LINTLIBDIR)/llib-lX11.ln

         XLIBONLY = $(XONLYLIB)

      XEXTLIBSRC = $(LIBSRC)/Xext

SOXEXTREV = 6.4
DEPEXTENSIONLIB =
EXTENSIONLIB =  -lXext

LINTEXTENSION = $(LINTLIBDIR)/llib-lXext.ln

LINTEXTENSIONLIB = $(LINTEXTENSION)
          DEPXLIB = $(DEPEXTENSIONLIB) $(DEPXONLYLIB)
             XLIB = $(EXTENSIONLIB) $(XONLYLIB)
         LINTXLIB = $(LINTXONLYLIB)

    XSSLIBSRC = $(LIBSRC)/Xss

DEPXSSLIB = $(USRLIBDIR)/libXss.a
XSSLIB =  -lXss

LINTXSS = $(LINTLIBDIR)/llib-lXss.ln

    XXF86MISCLIBSRC = $(LIBSRC)/Xxf86misc

SOXXF86MISCREV = 1.0
DEPXXF86MISCLIB =
XXF86MISCLIB =  -lXxf86misc

LINTXXF86MISC = $(LINTLIBDIR)/llib-lXxf86misc.ln

    XXF86VMLIBSRC = $(LIBSRC)/Xxf86vm

SOXXF86VMREV = 1.0
DEPXXF86VMLIB =
XXF86VMLIB =  -lXxf86vm

LINTXXF86VM = $(LINTLIBDIR)/llib-lXxf86vm.ln

    XXF86DGALIBSRC = $(LIBSRC)/Xxf86dga

SOXXF86DGAREV = 1.0
DEPXXF86DGALIB =
XXF86DGALIB =  -lXxf86dga

LINTXXF86DGA = $(LINTLIBDIR)/llib-lXxf86dga.ln

    XXF86RUSHLIBSRC = $(LIBSRC)/Xxf86rush

DEPXXF86RUSHLIB = $(USRLIBDIR)/libXxf86rush.a
XXF86RUSHLIB =  -lXxf86rush

LINTXXF86RUSH = $(LINTLIBDIR)/llib-lXxf86rush.ln

    XVLIBSRC = $(LIBSRC)/Xv

SOXVREV = 1.0
DEPXVLIB =
XVLIB =  -lXv

LINTXV = $(LINTLIBDIR)/llib-lXv.ln

    XVMCLIBSRC = $(LIBSRC)/XvMC

DEPXVMCLIB = $(USRLIBDIR)/libXvMC.a
XVMCLIB =  -lXvMC

LINTXVMC = $(LINTLIBDIR)/llib-lXvMC.ln

    XINERAMALIBSRC = $(LIBSRC)/Xinerama

DEPXINERAMALIB = $(USRLIBDIR)/libXinerama.a
XINERAMALIB =  -lXinerama

LINTXINERAMA = $(LINTLIBDIR)/llib-lXinerama.ln

    DPSLIBSRC = $(LIBSRC)/dps

SODPSREV = 1.0
DEPDPSLIB =
DPSLIB =  -ldps

LINTDPS = $(LINTLIBDIR)/llib-ldps.ln

    DPSTKLIBSRC = $(LIBSRC)/dpstk

SODPSTKREV = 1.0
DEPDPSTKLIB =
DPSTKLIB =  -ldpstk

LINTDPSTK = $(LINTLIBDIR)/llib-ldpstk.ln

    PSRESLIBSRC = $(LIBSRC)/psres

SOPSRESREV = 1.0
DEPPSRESLIB =
PSRESLIB =  -lpsres

LINTPSRES = $(LINTLIBDIR)/llib-lpsres.ln

    GLULIBSRC = $(LIBSRC)/GLU

SOGLUREV = 1.3
DEPGLULIB =
GLULIB =  -lGLU

LINTGLU = $(LINTLIBDIR)/llib-lGLU.ln

    GLXLIBSRC = $(LIBSRC)/GL

SOGLREV = 1.2
DEPGLXLIB =
GLXLIB =  -lGL

LINTGLX = $(LINTLIBDIR)/llib-lGL.ln

    GLWIDGETSRC = $(LIBSRC)/GLw

DEPGLWLIB = $(USRLIBDIR)/libGLw.a
GLWLIB =  -lGLw

LINTGLW = $(LINTLIBDIR)/llib-lGLw.ln

    XRENDERLIBSRC = $(LIBSRC)/Xrender

SOXRENDERREV = 1.1
DEPXRENDERLIB =
XRENDERLIB =  -lXrender

LINTXRENDER = $(LINTLIBDIR)/llib-lXrender.ln

    XRANDRRLIBSRC = $(LIBSRC)/Xrandr

SOXRANDRREV = 1.0
DEPXRANDRLIB =
XRANDRLIB =  -lXrandr

LINTXRANDR = $(LINTLIBDIR)/llib-lXrandr.ln

    XFONTCACHELIBSRC = $(LIBSRC)/Xfontcache

DEPXFONTCACHELIB = $(USRLIBDIR)/libXfontcache.a
XFONTCACHELIB =  -lXfontcache

LINTXFONTCACHE = $(LINTLIBDIR)/llib-lXfontcache.ln

         XAUTHSRC = $(LIBSRC)/Xau

DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
XAUTHLIB =  -lXau

LINTXAUTH = $(LINTLIBDIR)/llib-lXau.ln

      XDMCPLIBSRC = $(LIBSRC)/Xdmcp

DEPXDMCPLIB = $(USRLIBDIR)/libXdmcp.a
XDMCPLIB =  -lXdmcp

LINTXDMCP = $(LINTLIBDIR)/llib-lXdmcp.ln

           XMUSRC = $(LIBSRC)/Xmu

SOXMUREV = 6.2
DEPXMULIB =
XMULIB =  -lXmu

LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln

           XMUUSRC = $(LIBSRC)/Xmuu

SOXMUUREV = 1.0
DEPXMUULIB =
XMUULIB =  -lXmuu

LINTXMUU = $(LINTLIBDIR)/llib-lXmuu.ln

       OLDXLIBSRC = $(LIBSRC)/oldX

DEPOLDXLIB = $(USRLIBDIR)/liboldX.a
OLDXLIB =  -loldX

LINTOLDX = $(LINTLIBDIR)/llib-loldX.ln

         XPLIBSRC = $(LIBSRC)/Xp

SOXPREV = 6.2
DEPXPLIB =
XPLIB =  -lXp

LINTXP = $(LINTLIBDIR)/llib-lXp.ln

       TOOLKITSRC = $(LIBSRC)/Xt

SOXTREV = 6.0
DEPXTOOLONLYLIB =
XTOOLONLYLIB =  -lXt

LINTXTOOLONLY = $(LINTLIBDIR)/llib-lXt.ln

      DEPXTOOLLIB = $(DEPXTOOLONLYLIB) $(DEPSMLIB) $(DEPICELIB)
         XTOOLLIB = $(XTOOLONLYLIB) $(SMLIB) $(ICELIB)
     LINTXTOOLLIB = $(LINTXTOOLONLYLIB)

       XALIBSRC = $(LIBSRC)/Xa

SOXAREV = 1.0
DEPXALIB =
XALIB =  -lXa

LINTXA = $(LINTLIBDIR)/llib-lXa.ln

       AWIDGETSRC = $(LIBSRC)/Xaw

SOXAWREV = 7.0
DEPXAWLIB =
XAWLIB =  -lXaw

LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln

       AWIDGET6SRC = $(LIBSRC)/Xaw6

SOXAW6REV = 6.1
DEPXAW6LIB =
XAW6LIB =  -lXaw

LINTXAW6 = $(LINTLIBDIR)/llib-lXaw.ln

         XILIBSRC = $(LIBSRC)/Xi

SOXINPUTREV = 6.0
DEPXILIB =
XILIB =  -lXi

LINTXI = $(LINTLIBDIR)/llib-lXi.ln

      XTESTLIBSRC = $(LIBSRC)/Xtst

SOXTESTREV = 6.1
DEPXTESTLIB =
XTESTLIB =  -lXtst

LINTXTEST = $(LINTLIBDIR)/llib-lXtst.ln

        PEXLIBSRC = $(LIBSRC)/PEX5

SOPEXREV = 6.0
DEPPEXLIB =
PEXLIB =  -lPEX5

LINTPEX = $(LINTLIBDIR)/llib-lPEX5.ln

        XIELIBSRC = $(LIBSRC)/XIE

SOXIEREV = 6.0
DEPXIELIB =
XIELIB =  -lXIE

LINTXIE = $(LINTLIBDIR)/llib-lXIE.ln

      PHIGSLIBSRC = $(LIBSRC)/PHIGS

DEPPHIGSLIB = $(USRLIBDIR)/libphigs.a
PHIGSLIB =  -lphigs

LINTPHIGS = $(LINTLIBDIR)/llib-lphigs.ln

DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
XBSDLIB =  -lXbsd

LINTXBSD = $(LINTLIBDIR)/llib-lXbsd.ln

           ICESRC = $(LIBSRC)/ICE

SOICEREV = 6.3
DEPICELIB =
ICELIB =  -lICE

LINTICE = $(LINTLIBDIR)/llib-lICE.ln

            SMSRC = $(LIBSRC)/SM

SOSMREV = 6.0
DEPSMLIB =
SMLIB =  -lSM

LINTSM = $(LINTLIBDIR)/llib-lSM.ln

           XKEYSRC = $(LIBSRC)/Xkey

SOXKEYREV = 6.0
DEPXKEYLIB =
XKEYLIB =  -lXkey

LINTXKEY = $(LINTLIBDIR)/llib-lXkey.ln

         FSLIBSRC = $(LIBSRC)/FS

DEPFSLIB = $(USRLIBDIR)/libFS.a
FSLIB =  -lFS

LINTFS = $(LINTLIBDIR)/llib-lFS.ln

         FONTLIBSRC = $(LIBSRC)/font

SOFONTREV = 1.4
DEPFONTLIB =
FONTLIB = -L$(FREETYPELIBDIR) -L$(FONTLIBSRC)  -lXfont

LINTXFONT = $(LINTLIBDIR)/llib-lXfont.ln
#
SOFONTREV = 1.4
DEPXFONTLIB =
XFONTLIB =  -lXfont

LINTXFONT = $(LINTLIBDIR)/llib-lXfont.ln

     FONTSTUBLIBSRC = $(FONTLIBSRC)/stubs

DEPFONTSTUBLIB = $(USRLIBDIR)/libfntstubs.a
FONTSTUBLIB =  -lfntstubs

LINTFONTSTUB = $(LINTLIBDIR)/llib-lfntstubs.ln
         DEPFONTLIB = $(DEPXFONTLIB) $(DEPFONTSTUBLIB)
            FONTLIB = $(XFONTLIB) $(FONTSTUBLIB)

         FONTENCLIBSRC = $(LIBSRC)/fontenc

DEPXFONTENCLIB = $(USRLIBDIR)/libfontenc.a
XFONTENCLIB =  -lfontenc

LINTXFONTENC = $(LINTLIBDIR)/llib-lfontenc.ln

          XPMLIBSRC = $(LIBSRC)/Xpm

SOXPMREV = 4.11
DEPXPMLIB =
XPMLIB =  -lXpm

LINTXPM = $(LINTLIBDIR)/llib-lXpm.ln

          FREETYPE2LIBSRC = $(LIBSRC)/freetype2

SOFREETYPE2REV = 6.2
DEPFREETYPE2LIB =
FREETYPE2LIB =  -lfreetype

LINTFREETYPE2 = $(LINTLIBDIR)/llib-lfreetype.ln

FREETYPE2DIR = /usr
FREETYPE2LIBDIR = /usr/lib
FREETYPE2INCDIR = /usr/include/freetype2
FREETYPE2INCLUDES = -I$(FREETYPE2INCDIR)
FREETYPE2LIB = -L$(FREETYPE2LIBDIR) -lfreetype
FREETYPE2DEFINES = -DFREETYPE2

          XFTLIBSRC = $(LIBSRC)/Xft

SOXFTREV = 1.1
DEPXFTLIB =
XFTLIB =  -lXft

LINTXFT = $(LINTLIBDIR)/llib-lXft.ln

    XKBFILELIBSRC = $(LIBSRC)/xkbfile

DEPXKBFILELIB = $(USRLIBDIR)/libxkbfile.a
XKBFILELIB =  -lxkbfile

LINTXKBFILE = $(LINTLIBDIR)/llib-lxkbfile.ln

     XKBCOMPCMD = $(BINDIR)/xkbcomp

    XKBUILIBSRC = $(LIBSRC)/xkbui

DEPXKBUILIB = $(USRLIBDIR)/libxkbui.a
XKBUILIB =  -lxkbui

LINTXKBUI = $(LINTLIBDIR)/llib-lxkbui.ln

        XTRAPLIBSRC = $(LIBSRC)/XTrap

SOXTRAPREV = 6.4
DEPXTRAPLIB =
XTRAPLIB =  -lXTrap

LINTXTRAP = $(LINTLIBDIR)/llib-lXTrap.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)
         DEPLIBS4 = $(DEPLIBS)
         DEPLIBS5 = $(DEPLIBS)
         DEPLIBS6 = $(DEPLIBS)
         DEPLIBS7 = $(DEPLIBS)
         DEPLIBS8 = $(DEPLIBS)
         DEPLIBS9 = $(DEPLIBS)
         DEPLIBS10 = $(DEPLIBS)

              MTOP = $(TOP)

      UIL_INCLUDES = -I$(USRINCDIR)/uil

    MOTIFENVLIBDIR = $(USRLIBDIR)

      USRINCDIR = /usr/X11R6/include
         UIDDIR = $(LIBDIR)/uid
        TESTSRC = $(MTOP)/tests
        TESTLIB = $(TESTSRC)/lib
  GENERALSRCLIB = $(TESTSRC)/General/lib
  GENERALSRCBIN = $(TESTSRC)/General/bin
   MANUALSRCLIB = $(TESTSRC)/Manual/lib
   MANUALSRCBIN = $(TESTSRC)/Manual/bin
     AUTOSRCLIB = $(TESTSRC)/Auto/lib
     AUTOSRCBIN = $(TESTSRC)/Auto/bin
       COMMONPP = $(GENERALSRCBIN)/Commonpp
         GENRUN = $(GENERALSRCBIN)/Genrun
         MANRUN = $(GENERALSRCBIN)/Manrun

     TESTCOMSRC = $(MANUALSRCLIB)/Common

    BUILDDOCDIR = $(BUILDINCROOT)/doc
    BUILDLOCDIR = $(BUILDINCROOT)/localized

    MTOOLKITSRC = $(TOOLKITSRC)

    MINCLUDESRC = $(MTOP)/include
        MDOCSRC = $(MTOP)/doc
        MLOCSRC = $(MTOP)/localized

        MLIBSRC = $(MTOP)/lib
     MCLIENTSRC = $(MTOP)/clients
       MDEMOSRC = $(MTOP)/demos
     MWIDGETSRC = $(MLIBSRC)/Xm
   MRESOURCESRC = $(MLIBSRC)/Mrm
         UILSRC = $(MCLIENTSRC)/uil

            UIL = uil
         DEPUIL = $(BINDIR)/uil

   XMEXTRA_LIBS =

SOXMREV = 2.1
DEPXMLIB =
XMLIB =  -lXm

LINTXM = $(LINTLIBDIR)/llib-lXm.ln

SOMRMREV = 2.1
DEPMRESOURCELIB =
MRESOURCELIB =  -lMrm

LINTMRESOURCE = $(LINTLIBDIR)/llib-lMrm.ln

SOUILREV = 2.1
DEPUILLIB =
UILLIB =  -lUil

LINTUIL = $(LINTLIBDIR)/llib-lUil.ln

SOMCOMMONREV = 2.1
DEPTESTCOMLIB =
TESTCOMLIB =  -lMCommon

LINTTESTCOM = $(LINTLIBDIR)/llib-lMCommon.ln

TESTUILCOMLIB = $(TESTCOMSRC)/libMCommonUil.a

  LINTMRESOURCE = $(MRESOURCESRC)/libMrm.a
LINTXMWIDGETLIB = $(MWIDGETSRC)/llib-l/Xm.ln
     LINTXMTOOL = $(MTOOLKITSRC)/llib-lXt.ln
     LINTUILLIB = $(UILSRC)/llib-lUil.ln

      YACCFLAGS =
       UILFLAGS =
    GENCATFLAGS =
         GENCAT = gencat $(GENCATFLAGS)
      MKCATTOOL = $(MLOCSRC)/util/mkcatdefs

         RM_CMD = $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut  *.Dat

        DEPLIBS = $(DEPXMLIB) $(DEPXTOOLLIB) $(DEPXPLIB) $(DEPXLIB)

        DEPLIBS1 = $(DEPLIBS)
        DEPLIBS2 = $(DEPLIBS)
        DEPLIBS3 = $(DEPLIBS)

XMULIBONLY = -lXmu
XMULIB = $(XMULIBONLY) $(XTOOLLIB) $(XLIB)

        CONFIGDIR = $(LIBDIR)/config

    USRLIBDIRPATH = $(USRLIBDIR)
        LDPRELIBS = -L$(USRLIBDIR)
       LDPOSTLIBS =
     TOP_INCLUDES = -I$(INCROOT) $(TOP_MOTIF_INCLUDES) $(TOP_X_INCLUDES)
  PROJECT_DEFINES =

CXXPROJECT_DEFINES =

# ----------------------------------------------------------------------
# start of Imakefile

#  Destination directories. ##############################################

#  Where xplore config and pixmap files go.
XPLORELIBDIR = $(LIBDIR)/xplore

#  Set these if you want to install xplore in a non-standard location.
# BINDIR = /usr/local/bin
# LIBDIR = /usr/local/lib
# MANPATH = /usr/local/man

#  Libraries. ############################################################

#  Set XMINCDIR and XMLIBDIR as required by your system if the Motif
#  library is not on the standard path. (The following should work
#  for Solaris, on Linux systems usually no extra path is required.)
# XMINCDIR = -I/usr/dt/include
# XMLIBDIR = -L/usr/dt/lib

#  How to link the Motif library:
XMLIB = -lXm

#  Set XPMINCDIR and XPMLIBDIR as required by your system if libXpm is not
#  on the standard path. E.g. (Solaris, with software companion cd
#  installed in /opt/sfw):
# XPMINCDIR = -I/opt/sfw/include
# XPMLIBDIR = -L/opt/sfw/lib -R/opt/sfw/lib

#  How to link the XPM library
XPMLIB = -lXpm

#  Compilation options. ##################################################

#  Uncomment the following line if you want to compile xplore with gcc,
#  but gcc is not the default compiler on your system.
# #define USE_GCC

#  Debugging options. ####################################################
#  Uncomment this if you want to generate debug information:
# CDEBUGFLAGS = -g

#  System dependencies. ##################################################

  SYSDEP = -DFreeBSD

  SYSDEP = -DLINUX

# If your system is not SVR4 and neither matches one of the above, you
# might wish to uncomment one of the following and proceed with fingers
# crossed.

# SYSDEP		= -DSVR4
# SYSDEP		= -DAIX
# SYSDEP		= -DCONVEXOS
# SYSDEP		= -DDYNIX
# SYSDEP		= -DHPUX -D_HPUX_SOURCE
# SYSDEP		= -DFreeBSD
# SYSDEP		= -DLINUX
# SYSDEP		= -DOSF1
# SYSDEP		= -DSCO
# SYSDEP		= -DSGI
# SYSDEP		= -DSOLARIS
# SYSDEP		= -DSUNOS
# SYSDEP		= -DTOS
# SYSDEP		= -DULTRIX

#  Uncomment the next line if your system has the statvfs() system call
#  (default for SVR4, Solaris and SGI). Check this if interface.c won't
#  compile, or when your linker cannot resolve _statfs.
# STATVFS = -DUSE_STATVFS

XGINCDIR = -I./xg/include
XGLIBDIR = -L./xg
XGLIB = -lxg

all::
	@for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[ik]*) set +e;; esac; done; \
	for i in xg regexp scripts ;\
	do \
	echo "making" all "in $(CURRENT_DIR)/$$i..."; \
	$(MAKE) -C $$i $(MFLAGS) $(PARALLELMFLAGS)  all; \
	done

$(ONESUBDIR)/Makefile:
	@for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[n]*) executeit="no";; esac; done; \
	cd $(ONESUBDIR) && \
	if [ "$$executeit" != "no" ]; then \
	$(IMAKE_CMD) -DTOPDIR=$(IMAKETOP) -DCURDIR=$(ONECURDIR)$(ONESUBDIR); \
	fi;

Makefiles::
	-@for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[ik]*) set +e;; esac; done; \
	for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[n]*) executeit="no";; esac; done; \
	for i in xg regexp scripts ;\
	do \
	case "$(CURRENT_DIR)" in \
	.) curdir= ;; \
	*) curdir=$(CURRENT_DIR)/ ;; \
	esac; \
	echo "making Makefiles in $$curdir$$i..."; \
	itmp=`echo $$i | sed -e 's;^\./;;g' -e 's;/\./;/;g'`; \
	curtmp="$(CURRENT_DIR)" \
	toptmp=""; \
	case "$$itmp" in \
	../?*) \
	while echo "$$itmp" | grep '^\.\./' > /dev/null;\
	do \
	toptmp="/`basename $$curtmp`$$toptmp"; \
	curtmp="`dirname $$curtmp`"; \
	itmp="`echo $$itmp | sed 's;\.\./;;'`"; \
	done \
	;; \
	esac; \
	case "$$itmp" in \
	*/?*/?*/?*/?*)	newtop=../../../../..;; \
	*/?*/?*/?*)	newtop=../../../..;; \
	*/?*/?*)	newtop=../../..;; \
	*/?*)		newtop=../..;; \
	*)		newtop=..;; \
	esac; \
	newtop="$$newtop$$toptmp"; \
	case "$(TOP)" in \
	/?*) imaketop=$(TOP) \
	imakeprefix= ;; \
	.) imaketop=$$newtop \
	imakeprefix=$$newtop/ ;; \
	*) imaketop=$$newtop/$(TOP) \
	imakeprefix=$$newtop/ ;; \
	esac; \
	$(RM) $$i/Makefile.bak; \
	if [ -f $$i/Makefile ]; then \
	echo "	$(MV) Makefile Makefile.bak"; \
	if [ "$$executeit" != "no" ]; then \
	$(MV) $$i/Makefile $$i/Makefile.bak; \
	fi; \
	fi; \
	$(MAKE) $(MFLAGS) $(MAKE_OPTS) ONESUBDIR=$$i ONECURDIR=$$curdir IMAKETOP=$$imaketop IMAKEPREFIX=$$imakeprefix $$i/Makefile; \
	if [ -d $$i ] ; then \
	cd $$i; \
	$(MAKE) $(MFLAGS) Makefiles; \
	cd $$newtop; \
	else \
	exit 1; \
	fi; \
	done

cleandir::
	@for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[ik]*) set +e;; esac; done; \
	for i in xg regexp scripts ;\
	do \
	echo "cleaning" "in $(CURRENT_DIR)/$$i..."; \
	$(MAKE) -C $$i $(MFLAGS) $(PARALLELMFLAGS)  cleandir; \
	done

depend::
	@for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[ik]*) set +e;; esac; done; \
	for i in xg regexp scripts ;\
	do \
	echo "depending" "in $(CURRENT_DIR)/$$i..."; \
	$(MAKE) -C $$i $(MFLAGS) $(PARALLELMFLAGS)  depend; \
	done

install::
	@for flag in ${MAKEFLAGS} ''; do \
	case "$$flag" in *=*) ;; *[ik]*) set +e;; esac; done; \
	for i in scripts ;\
	do \
	echo "installing" "in $(CURRENT_DIR)/$$i..."; \
	$(MAKE) -C $$i $(MFLAGS) $(PARALLELMFLAGS) DESTDIR=$(DESTDIR) install; \
	done

Xplore.ad: Xplore.sed
	sed -e 's?@XPLORELIBDIR@?$(XPLORELIBDIR)?g' <Xplore.sed >$@

etc/Manual: xplore.man
	rman -f HTML xplore.man | sed -e '1,3d' >$@

install:: Xplore.ad
	@if [ -d $(DESTDIR)$(XAPPLOADDIR) ]; then \
	set +x; \
	else \
	if [ -h $(DESTDIR)$(XAPPLOADDIR) ]; then \
	(set -x; rm -f $(DESTDIR)$(XAPPLOADDIR)); \
	fi; \
	(set -x; $(MKDIRHIER) $(DESTDIR)$(XAPPLOADDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTAPPFLAGS) Xplore.ad $(DESTDIR)$(XAPPLOADDIR)/Xplore

install:: all
	@if [ -d $(DESTDIR)$(XPLORELIBDIR) ]; then \
	set +x; \
	else \
	if [ -h $(DESTDIR)$(XPLORELIBDIR) ]; then \
	(set -x; rm -f $(DESTDIR)$(XPLORELIBDIR)); \
	fi; \
	(set -x; $(MKDIRHIER) $(DESTDIR)$(XPLORELIBDIR)); \
	fi
	$(INSTALL) -c $(INSTDATFLAGS) system.xplorerc $(DESTDIR)$(XPLORELIBDIR)/system.xplorerc

	$(INSTALL) -c $(INSTDATFLAGS) magic $(DESTDIR)$(XPLORELIBDIR)/magic
	cp -R etc $(DESTDIR)$(XPLORELIBDIR)
	cp -R icons $(DESTDIR)$(XPLORELIBDIR)
	cp -R shelf $(DESTDIR)$(XPLORELIBDIR)
	cp -R schemes $(DESTDIR)$(XPLORELIBDIR)

PROGRAMS	= xplore xploretype

DEFINES		= -DXPLORELIBDIR=\"$(XPLORELIBDIR)\" -DCPP="\"$(CPP)\"" $(SYSDEP) $(STATVFS)

EXTRA_INCLUDES	= -I./regexp -I./icons $(XGINCDIR) $(XMINCDIR) $(XPMINCDIR)

SRCS1 = callbacks.c curdir.c devmount.c dialogs.c dirs.c error.c fileops.c 	ftype.c icons.c interface.c magic.c menus.c mnttable.c signals.c 	util.c xplore.c

OBJS1 = callbacks.o curdir.o devmount.o dialogs.o dirs.o error.o fileops.o 	ftype.o icons.o interface.o magic.o menus.o mnttable.o parse.o 	signals.o util.o xplore.o

DEPLIBS1	=  ./xg/libxg.a ./regexp/libregexp.a
SYSLIBS1	=  $(XGLIBDIR) $(XMLIBDIR) $(XPMLIBDIR) -L./regexp -lregexp 	$(XGLIB) $(XMLIB) $(XPMLIB) $(XTOOLLIB) $(XMULIB) $(XLIB)

all:: defaults.h setup etc/Manual
depend:: defaults.h

setup:
	cp scripts/setup.script setup

defaults.h: Xplore.ad
	./ad2c Xplore.ad > defaults.h

cleandir::
	$(RM) defaults.h setup Xplore.ad

parse.o: parse.c lex.c xplore.h parse.h

 OBJS = $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(OBJS5) \
 $(OBJS6) $(OBJS7) $(OBJS8) $(OBJS9) $(OBJS10)
 SRCS = $(SRCS1) $(SRCS2) $(SRCS3) $(SRCS4) $(SRCS5) \
 $(SRCS6) $(SRCS7) $(SRCS8) $(SRCS9) $(SRCS10)

all:: $(PROGRAMS)

xplore: $(OBJS1) $(DEPLIBS1)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS1)  $(LDLIBS) $(SYSLIBS1) $(EXTRA_LOAD_FLAGS)

install:: xplore
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
	set +x; \
	else \
	if [ -h $(DESTDIR)$(BINDIR) ]; then \
	(set -x; rm -f $(DESTDIR)$(BINDIR)); \
	fi; \
	(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  xplore $(DESTDIR)$(BINDIR)/xplore

all:: xplore.$(MANNEWSUFFIX)

xplore.$(MANNEWSUFFIX): xplore.$(MANSRCSUFFIX)
	$(RM) $@
	cd `dirname xplore` && \
	$(LN) `basename xplore.$(MANSRCSUFFIX)` `basename $@`

cleandir::
	$(RM) xplore.$(MANNEWSUFFIX)

install.man:: xplore.$(MANNEWSUFFIX)
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
	set +x; \
	else \
	if [ -h $(DESTDIR)$(MANDIR) ]; then \
	(set -x; rm -f $(DESTDIR)$(MANDIR)); \
	fi; \
	(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) xplore.$(MANNEWSUFFIX) $(DESTDIR)$(MANDIR)/xplore.$(MANSUFFIX)

depend::
	$(DEPEND) $(DEPENDFLAGS) -- $(ALLDEFINES) $(DEPEND_DEFINES) -- $(SRCS)

lint:
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)
lint1:
	$(LINT) $(LINTFLAGS) $(FILE) $(LINTLIBS)

cleandir::
	$(RM) $(PROGRAMS)

SRCS2		= xploretype.c
OBJS2		= xploretype.o magic.o util.o
DEPLIBS2	= ./regexp/libregexp.a
SYSLIBS2	=  -L./regexp -lregexp

xploretype: $(OBJS2) $(DEPLIBS2)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS2)  $(LDLIBS) $(SYSLIBS2) $(EXTRA_LOAD_FLAGS)

install:: xploretype
	@if [ -d $(DESTDIR)$(BINDIR) ]; then \
	set +x; \
	else \
	if [ -h $(DESTDIR)$(BINDIR) ]; then \
	(set -x; rm -f $(DESTDIR)$(BINDIR)); \
	fi; \
	(set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  xploretype $(DESTDIR)$(BINDIR)/xploretype

all:: xploretype.$(MANNEWSUFFIX)

xploretype.$(MANNEWSUFFIX): xploretype.$(MANSRCSUFFIX)
	$(RM) $@
	cd `dirname xploretype` && \
	$(LN) `basename xploretype.$(MANSRCSUFFIX)` `basename $@`

cleandir::
	$(RM) xploretype.$(MANNEWSUFFIX)

install.man:: xploretype.$(MANNEWSUFFIX)
	@if [ -d $(DESTDIR)$(MANDIR) ]; then \
	set +x; \
	else \
	if [ -h $(DESTDIR)$(MANDIR) ]; then \
	(set -x; rm -f $(DESTDIR)$(MANDIR)); \
	fi; \
	(set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); \
	fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) xploretype.$(MANNEWSUFFIX) $(DESTDIR)$(MANDIR)/xploretype.$(MANSUFFIX)

# ----------------------------------------------------------------------
# common rules for all Makefiles - do not edit

.c.i:
	$(RM) $@
	 $(CC) -E $(CFLAGS) $(_NOOP_) $*.c > $@

.SUFFIXES: .s

.c.s:
	$(RM) $@
	 $(CC) -S $(CFLAGS) $(_NOOP_) $*.c

emptyrule::

cleandir::
	$(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut  "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

man_keywords::

html_index::

clean:: cleandir

distclean:: cleandir

# ----------------------------------------------------------------------
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

install.sdk::
	@echo "install.sdk in $(CURRENT_DIR) done"

Makefiles::

includes::

depend::

distclean::
	$(RM) Makefile

# ----------------------------------------------------------------------
# dependencies generated by makedepend

# DO NOT DELETE
callbacks.o: callbacks.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h callbacks.h \
 xg/include/Tabs.h curdir.h dirs.h icons.h devmount.h dialogs.h \
 error.h fileops.h ftype.h interface.h menus.h parse.h util.h \
 /usr/X11R6/include/Xm/XmAll.h /usr/X11R6/include/Xm/ArrowB.h \
 /usr/X11R6/include/Xm/ArrowBG.h /usr/X11R6/include/Xm/AtomMgr.h \
 /usr/X11R6/include/Xm/BulletinB.h /usr/X11R6/include/Xm/CascadeB.h \
 /usr/X11R6/include/Xm/CascadeBG.h /usr/X11R6/include/Xm/ComboBox.h \
 /usr/X11R6/include/Xm/Command.h /usr/X11R6/include/Xm/Container.h \
 /usr/X11R6/include/Xm/CutPaste.h /usr/X11R6/include/Xm/DialogS.h \
 /usr/X11R6/include/Xm/DragDrop.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/DrawingA.h /usr/X11R6/include/Xm/DrawnB.h \
 /usr/X11R6/include/Xm/FileSB.h /usr/X11R6/include/Xm/Form.h \
 /usr/X11R6/include/Xm/Frame.h /usr/X11R6/include/Xm/GrabShell.h \
 /usr/X11R6/include/Xm/IconFile.h /usr/X11R6/include/Xm/IconG.h \
 /usr/X11R6/include/Xm/IconH.h /usr/X11R6/include/Xm/Label.h \
 /usr/X11R6/include/Xm/LabelG.h /usr/X11R6/include/Xm/List.h \
 /usr/X11R6/include/Xm/MainW.h /usr/X11R6/include/Xm/MenuShell.h \
 /usr/X11R6/include/Xm/MessageB.h /usr/X11R6/include/Xm/MwmUtil.h \
 /usr/X11R6/include/X11/Xmd.h /usr/X11R6/include/Xm/Notebook.h \
 /usr/X11R6/include/Xm/PanedW.h /usr/X11R6/include/Xm/Print.h \
 /usr/X11R6/include/Xm/Protocols.h /usr/X11R6/include/Xm/PushB.h \
 /usr/X11R6/include/Xm/PushBG.h /usr/X11R6/include/Xm/RepType.h \
 /usr/X11R6/include/Xm/RowColumn.h /usr/X11R6/include/Xm/SSpinB.h \
 /usr/X11R6/include/Xm/Scale.h /usr/X11R6/include/Xm/Screen.h \
 /usr/X11R6/include/Xm/ScrollBar.h /usr/X11R6/include/Xm/ScrolledW.h \
 /usr/X11R6/include/Xm/SelectioB.h /usr/X11R6/include/Xm/SeparatoG.h \
 /usr/X11R6/include/Xm/Separator.h /usr/X11R6/include/Xm/SpinB.h \
 /usr/X11R6/include/Xm/Text.h /usr/X11R6/include/Xm/TextF.h \
 /usr/X11R6/include/Xm/ToggleB.h /usr/X11R6/include/Xm/ToggleBG.h
curdir.o: curdir.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h curdir.h \
 dirs.h icons.h fileops.h ftype.h menus.h mnttable.h util.h
devmount.o: devmount.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h devmount.h \
 icons.h mnttable.h util.h
dialogs.o: dialogs.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h dialogs.h \
 icons.h callbacks.h xg/include/Tabs.h devmount.h ftype.h interface.h \
 dirs.h util.h /usr/X11R6/include/Xm/XmAll.h \
 /usr/X11R6/include/Xm/ArrowB.h /usr/X11R6/include/Xm/ArrowBG.h \
 /usr/X11R6/include/Xm/AtomMgr.h /usr/X11R6/include/Xm/BulletinB.h \
 /usr/X11R6/include/Xm/CascadeB.h /usr/X11R6/include/Xm/CascadeBG.h \
 /usr/X11R6/include/Xm/ComboBox.h /usr/X11R6/include/Xm/Command.h \
 /usr/X11R6/include/Xm/Container.h /usr/X11R6/include/Xm/CutPaste.h \
 /usr/X11R6/include/Xm/DialogS.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragIcon.h /usr/X11R6/include/Xm/DropTrans.h \
 /usr/X11R6/include/Xm/DragOverS.h /usr/X11R6/include/Xm/DrawingA.h \
 /usr/X11R6/include/Xm/DrawnB.h /usr/X11R6/include/Xm/FileSB.h \
 /usr/X11R6/include/Xm/Form.h /usr/X11R6/include/Xm/Frame.h \
 /usr/X11R6/include/Xm/GrabShell.h /usr/X11R6/include/Xm/IconFile.h \
 /usr/X11R6/include/Xm/IconG.h /usr/X11R6/include/Xm/IconH.h \
 /usr/X11R6/include/Xm/Label.h /usr/X11R6/include/Xm/LabelG.h \
 /usr/X11R6/include/Xm/List.h /usr/X11R6/include/Xm/MainW.h \
 /usr/X11R6/include/Xm/MenuShell.h /usr/X11R6/include/Xm/MessageB.h \
 /usr/X11R6/include/Xm/MwmUtil.h /usr/X11R6/include/X11/Xmd.h \
 /usr/X11R6/include/Xm/Notebook.h /usr/X11R6/include/Xm/PanedW.h \
 /usr/X11R6/include/Xm/Print.h /usr/X11R6/include/Xm/Protocols.h \
 /usr/X11R6/include/Xm/PushB.h /usr/X11R6/include/Xm/PushBG.h \
 /usr/X11R6/include/Xm/RepType.h /usr/X11R6/include/Xm/RowColumn.h \
 /usr/X11R6/include/Xm/SSpinB.h /usr/X11R6/include/Xm/Scale.h \
 /usr/X11R6/include/Xm/Screen.h /usr/X11R6/include/Xm/ScrollBar.h \
 /usr/X11R6/include/Xm/ScrolledW.h /usr/X11R6/include/Xm/SelectioB.h \
 /usr/X11R6/include/Xm/SeparatoG.h /usr/X11R6/include/Xm/Separator.h \
 /usr/X11R6/include/Xm/SpinB.h /usr/X11R6/include/Xm/Text.h \
 /usr/X11R6/include/Xm/TextF.h /usr/X11R6/include/Xm/ToggleB.h \
 /usr/X11R6/include/Xm/ToggleBG.h
dirs.o: dirs.c xplore.h /usr/include/alloca.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h dirs.h \
 icons.h devmount.h dialogs.h error.h ftype.h util.h
error.o: error.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h error.h \
 dialogs.h icons.h
fileops.o: fileops.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h fileops.h \
 dirs.h icons.h devmount.h dialogs.h error.h ftype.h signals.h util.h
ftype.o: ftype.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h ftype.h \
 icons.h util.h
icons.o: icons.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h icons.h \
 util.h icons/file.xpm icons/file_bad.xpm icons/file_link.xpm \
 icons/file_link_bad.xpm icons/folder.xpm icons/folder_bad.xpm \
 icons/folder_up.xpm icons/folder_link.xpm icons/app.xpm \
 icons/app_link.xpm icons/file_small.xpm icons/file_bad_small.xpm \
 icons/file_link_small.xpm icons/file_link_bad_small.xpm \
 icons/folder_small.xpm icons/folder_bad_small.xpm \
 icons/folder_up_small.xpm icons/folder_link_small.xpm \
 icons/app_small.xpm icons/app_link_small.xpm icons/files.xpm \
 icons/exec.xpm
interface.o: interface.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h interface.h \
 dirs.h icons.h callbacks.h xg/include/Tabs.h curdir.h devmount.h \
 dialogs.h error.h fileops.h ftype.h menus.h parse.h signals.h util.h \
 /usr/X11R6/include/X11/cursorfont.h /usr/X11R6/include/X11/keysym.h \
 /usr/X11R6/include/X11/keysymdef.h /usr/X11R6/include/Xm/XmAll.h \
 /usr/X11R6/include/Xm/ArrowB.h /usr/X11R6/include/Xm/ArrowBG.h \
 /usr/X11R6/include/Xm/AtomMgr.h /usr/X11R6/include/Xm/BulletinB.h \
 /usr/X11R6/include/Xm/CascadeB.h /usr/X11R6/include/Xm/CascadeBG.h \
 /usr/X11R6/include/Xm/ComboBox.h /usr/X11R6/include/Xm/Command.h \
 /usr/X11R6/include/Xm/Container.h /usr/X11R6/include/Xm/CutPaste.h \
 /usr/X11R6/include/Xm/DialogS.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragIcon.h /usr/X11R6/include/Xm/DropTrans.h \
 /usr/X11R6/include/Xm/DragOverS.h /usr/X11R6/include/Xm/DrawingA.h \
 /usr/X11R6/include/Xm/DrawnB.h /usr/X11R6/include/Xm/FileSB.h \
 /usr/X11R6/include/Xm/Form.h /usr/X11R6/include/Xm/Frame.h \
 /usr/X11R6/include/Xm/GrabShell.h /usr/X11R6/include/Xm/IconFile.h \
 /usr/X11R6/include/Xm/IconG.h /usr/X11R6/include/Xm/IconH.h \
 /usr/X11R6/include/Xm/Label.h /usr/X11R6/include/Xm/LabelG.h \
 /usr/X11R6/include/Xm/List.h /usr/X11R6/include/Xm/MainW.h \
 /usr/X11R6/include/Xm/MenuShell.h /usr/X11R6/include/Xm/MessageB.h \
 /usr/X11R6/include/Xm/MwmUtil.h /usr/X11R6/include/X11/Xmd.h \
 /usr/X11R6/include/Xm/Notebook.h /usr/X11R6/include/Xm/PanedW.h \
 /usr/X11R6/include/Xm/Print.h /usr/X11R6/include/Xm/Protocols.h \
 /usr/X11R6/include/Xm/PushB.h /usr/X11R6/include/Xm/PushBG.h \
 /usr/X11R6/include/Xm/RepType.h /usr/X11R6/include/Xm/RowColumn.h \
 /usr/X11R6/include/Xm/SSpinB.h /usr/X11R6/include/Xm/Scale.h \
 /usr/X11R6/include/Xm/Screen.h /usr/X11R6/include/Xm/ScrollBar.h \
 /usr/X11R6/include/Xm/ScrolledW.h /usr/X11R6/include/Xm/SelectioB.h \
 /usr/X11R6/include/Xm/SeparatoG.h /usr/X11R6/include/Xm/Separator.h \
 /usr/X11R6/include/Xm/SpinB.h /usr/X11R6/include/Xm/Text.h \
 /usr/X11R6/include/Xm/TextF.h /usr/X11R6/include/Xm/ToggleB.h \
 /usr/X11R6/include/Xm/ToggleBG.h /usr/X11R6/include/Xm/TransferP.h \
 /usr/X11R6/include/X11/Xmu/Editres.h defaults.h
magic.o: magic.c /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/stdlib.h /usr/include/bits/waitflags.h \
 /usr/include/bits/waitstatus.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/types.h \
 /usr/include/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/bits/time.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/unistd.h \
 /usr/include/bits/posix_opt.h /usr/include/bits/confname.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/ctype.h \
 /usr/include/string.h /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h magic.h \
 regexp/regexp.h
menus.o: menus.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h menus.h
mnttable.o: mnttable.c mnttable.h /usr/include/stdlib.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/endian.h /usr/include/bits/endian.h \
 /usr/include/sys/types.h /usr/include/bits/types.h \
 /usr/include/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/bits/time.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/stdio.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/string.h /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/bits/xopen_lim.h \
 /usr/include/bits/wordsize.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/stat.h \
 /usr/include/bits/stat.h /usr/include/sys/vfs.h \
 /usr/include/sys/statfs.h /usr/include/bits/statfs.h \
 /usr/include/mntent.h /usr/include/paths.h
signals.o: signals.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h signals.h
util.o: util.c xplore.h /usr/include/alloca.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h util.h
xplore.o: xplore.c xplore.h /usr/include/alloca.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/bits/types.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/stdlib.h \
 /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h \
 /usr/include/sys/types.h /usr/include/time.h \
 /usr/include/sys/select.h /usr/include/bits/select.h \
 /usr/include/bits/sigset.h /usr/include/bits/time.h \
 /usr/include/sys/sysmacros.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/unistd.h /usr/include/bits/posix_opt.h \
 /usr/include/bits/confname.h /usr/include/string.h \
 /usr/include/dirent.h /usr/include/bits/dirent.h \
 /usr/include/bits/posix1_lim.h /usr/include/bits/local_lim.h \
 /usr/include/linux/limits.h /usr/include/pwd.h /usr/include/grp.h \
 /usr/include/fcntl.h /usr/include/bits/fcntl.h \
 /usr/include/sys/stat.h /usr/include/bits/stat.h \
 /usr/include/signal.h /usr/include/bits/signum.h \
 /usr/include/bits/siginfo.h /usr/include/bits/wordsize.h \
 /usr/include/bits/sigaction.h /usr/include/bits/sigcontext.h \
 /usr/include/asm/sigcontext.h /usr/include/bits/sigstack.h \
 /usr/include/ucontext.h /usr/include/sys/ucontext.h \
 /usr/include/errno.h /usr/include/bits/errno.h \
 /usr/include/linux/errno.h /usr/include/asm/errno.h \
 /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix2_lim.h \
 /usr/include/bits/xopen_lim.h /usr/include/linux/param.h \
 /usr/include/asm/param.h /usr/include/sys/wait.h \
 /usr/include/sys/resource.h /usr/include/bits/resource.h \
 /usr/include/sys/vfs.h /usr/include/sys/statfs.h \
 /usr/include/bits/statfs.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/X11/extensions/Print.h \
 /usr/X11R6/include/X11/Xauth.h /usr/X11R6/include/X11/Xfuncs.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h /usr/X11R6/include/X11/xpm.h callbacks.h \
 xg/include/Tabs.h dialogs.h icons.h fileops.h dirs.h interface.h \
 mnttable.h parse.h signals.h util.h
xploretype.o: xploretype.c /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/gnu/stubs.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stddef.h \
 /usr/include/bits/types.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/wchar.h \
 /usr/include/bits/wchar.h /usr/include/gconv.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/stdarg.h \
 /usr/include/bits/stdio_lim.h /usr/include/getopt.h \
 /usr/include/stdlib.h /usr/include/bits/waitflags.h \
 /usr/include/bits/waitstatus.h /usr/include/endian.h \
 /usr/include/bits/endian.h /usr/include/sys/types.h \
 /usr/include/time.h /usr/include/sys/select.h \
 /usr/include/bits/select.h /usr/include/bits/sigset.h \
 /usr/include/bits/time.h /usr/include/sys/sysmacros.h \
 /usr/include/alloca.h /usr/include/sys/param.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/limits.h \
 /usr/lib/gcc-lib/i486-suse-linux/2.95.3/include/syslimits.h \
 /usr/include/limits.h /usr/include/bits/posix1_lim.h \
 /usr/include/bits/local_lim.h /usr/include/linux/limits.h \
 /usr/include/bits/posix2_lim.h /usr/include/bits/xopen_lim.h \
 /usr/include/bits/wordsize.h /usr/include/linux/param.h \
 /usr/include/asm/param.h
